### PR TITLE
Upgrade master to a single Unified CDC service

### PR DESCRIPTION
**Pull request by dartartem**

### CODE REVIEW

**Comment by dartartem** [comment]
Updated master to use unified cdc with old style configuration.

**Comment by cer** [comment]
@dartartem please fix conflicts

**Comment by dartartem** [comment]
> @dartartem please fix conflicts

Done

**Comment by cer** [comment]
Merged into wip-unified-cdc

**Comment by cer** [comment]
Merged into wip-unified-cdc

**Pull request closed without merging**
